### ISSUE TITLE
Nothing appears in the application window

### ISSUE THREAD

**Issue by asitemade4u** [qubus-ai/qubus#4] opened 2019-11-24 22:53 UTC
Me again.
Now that the application was successfully built, I did a `npm run qubus` from the qubus directory, both as a user and as an administrator (using `sudo`).
In either cases, nothing is displayed within the application widow.
Here are the steps:

1. at first opening, the **Settings** dialog displays. I can't use **GraphicMagic** which is only available on Windows.
1. I choose **Stanem** as a map provider (it is the default anyway).
1. Then I create a project with the **plus** sign.
1. I choose the folder full of JPGs, keep all other fields as is.
1. The window of the project appears, the (very fancy) progress thermometers, blue and pink are displayed but neither map nor photos are displayed.

As I launched Qubus from the terminal, here are the many repetitive errors that are reported:

`(electron:16485): dconf-WARNING **: 17:45:26.606: failed to commit changes to dconf: 
Transport « disabled » inconnu ou non pris en charge pour l’adresse « disabled: »
`

**Comment by asitemade4u** [comment] 2019-11-24 22:54
Ah, one more thing: I have the last version of **ImageMagick** installed on the computer.

**Comment by qubus-ai** [comment] 2019-11-25 20:26
Hi,
The issue reported by you, most probably is caused by incorrect files permissions. Running "npm run qubus" command as sudoer, created ~/.cache/dconf with permission for only root user, which resulted in dconf-WARNING .
The same applies  for the problem with adding project. It might have been caused as well by incorrect file permission for ~/.config/qubus directory.

I recommend to remove the following directories:
~/.cache/dconf
~/.config/qubus
and from the directory with images you added to project list, please remove images.json file which most probably has incorrect permission settings.

After cleaning, please run "npm run qubus" without sudo.
Generally, unless it is need by special system setting, all command for qubus should be run without sudo:

npm install
npm run build-release
npm run qubus

**Comment by qubus-ai** [comment] 2019-11-25 20:30
For GraphicsMagic on Ubuntu, I recommend: 

sudo apt-get install graphicsmagick

**Comment by asitemade4u** [comment] 2019-11-26 16:55
Thank you so much for the response!

It compiled perfectly + it works, but still several issues:

 1. the image folder is correctly read *except when the images are above
    a certain size*: a 15MB JPG image won't be read, which is an issue
    for me as I would use Qubus to geolocate images from my DSLR
 2. The *geolocation on the map is wrong*, and I assume you inverted
    West and East
     1. the STANEM map transported me in Kirghistan, at the confines of
        China -- all pictures were taken in NYC, USA
     2. So I switched to MAPNIK: the same
     3. HOT located me in the midst of the Indian Ocean
     4. Same location with BZH (the first one)
     5. The second BZH locates me again in Kirghistan

Best,

Stephen

**Comment by qubus-ai** [comment] 2019-11-26 20:34
Hi,
Thank you for reporting the issue with coordinates. You were right West coordinates were treated as East. It should be fixed now, please checkout the repository and re-initialize the project.
As for image size, if you provide sample data I can investigate the problem.

**Comment by qubus-ai** [comment] 2019-12-15 19:21
Hi @asitemade4u ,
Could you confirm the issue is fixed now?

**Closed as completed** 2020-01-02 09:30 UTC
